/** Field guide for Company pricing document (sell + known costs + crews/contacts). */
export type PricingGuideRow = {
  label: string;
  unit: string;
  cost?: number;
  sellPhx?: number;
  sellTuc?: number;
  sellNorth?: number;
  key?: string;
  note?: string;
};

export type PricingGuideSection = {
  title: string;
  /** Labor = package/crew/sells/adders · Materials = SRS + Miller book costs */
  pane: 'labor' | 'materials';
  supplier?: 'SRS' | 'Miller';
  rows: PricingGuideRow[];
};

/** Locked sell adder for high-profile hip & ridge (customer estimate). */
export const HIGH_PROFILE_RIDGE_SELL = 250;

export const PRICING_GUIDE: PricingGuideSection[] = [
  {
    title: 'Shingle package sells',
    pane: 'labor',
    rows: [
      { key: 'cambridge', label: 'IKO Cambridge', unit: '/sq', cost: 89, sellPhx: 450, sellTuc: 475, sellNorth: 500 },
      { key: 'dynasty', label: 'IKO Dynasty', unit: '/sq', cost: 94, sellPhx: 475, sellTuc: 500, sellNorth: 525 },
      { key: 'armourshake', label: 'IKO Armourshake', unit: '/sq', cost: 230, sellPhx: 610, sellTuc: 635, sellNorth: 660 },
      { key: 'gaf_hdz', label: 'GAF Timberline HDZ', unit: '/sq', cost: 130, sellPhx: 475, sellTuc: 500, sellNorth: 525 },
      { key: 'gaf_natural_shadow', label: 'GAF Natural Shadow', unit: '/sq', cost: 129, sellPhx: 450, sellTuc: 475, sellNorth: 500 },
      { key: 'owens_oakridge', label: 'Owens Corning Oakridge', unit: '/sq', cost: 110, sellPhx: 475, sellTuc: 500, sellNorth: 525 },
      { key: 'owens_duration', label: 'Owens Corning Duration', unit: '/sq', cost: 118, sellPhx: 500, sellTuc: 525, sellNorth: 550 },
      { key: 'owens_duration_designer', label: 'Owens Corning Duration Designer', unit: '/sq', cost: 118, sellPhx: 500, sellTuc: 525, sellNorth: 550, note: 'Same as Duration' },
      { key: 'certainteed_landmark', label: 'CertainTeed Landmark', unit: '/sq', cost: 117, sellPhx: 500, sellTuc: 525, sellNorth: 550 },
      { key: 'certainteed_patriot_xl', label: 'CertainTeed Patriot XL', unit: '/sq', cost: 103, sellPhx: 485, sellTuc: 510, sellNorth: 535 },
      { key: 'malarkey_highlander', label: 'Malarkey Highlander', unit: '/sq', cost: 154, sellPhx: 535, sellTuc: 560, sellNorth: 585 },
      { key: 'malarkey_vista', label: 'Malarkey Vista', unit: '/sq', cost: 160, sellPhx: 540, sellTuc: 565, sellNorth: 590 },
    ],
  },
  {
    title: 'Adders — sell',
    pane: 'labor',
    rows: [
      { key: 'remove_layer', label: 'Remove additional layer', unit: '/sq', sellPhx: 20, sellTuc: 25, sellNorth: 25 },
      { key: 'osb', label: 'R&R OSB', unit: '/sheet', cost: 11, sellPhx: 80, sellTuc: 90, sellNorth: 90 },
      { key: 'fascia', label: 'R&R Fascia', unit: '/LF', sellPhx: 15, sellTuc: 18, sellNorth: 18 },
      { key: 'fascia_2x6', label: 'R&R Fascia 2x6', unit: '/LF', sellPhx: 15, sellTuc: 18, sellNorth: 18 },
      { key: 'fascia_2x8', label: 'R&R Fascia 2x8', unit: '/LF', sellPhx: 18, sellTuc: 18, sellNorth: 18 },
      { key: 'ridge_vent', label: 'Install ridge vent', unit: '/LF', cost: 6, sellPhx: 13, sellTuc: 14, sellNorth: 14 },
      { key: 'skylight', label: 'HD Skylight', unit: '/ea', sellPhx: 525, sellTuc: 550, sellNorth: 550 },
      { key: 'shingle_mold', label: 'R&R Shingle mold', unit: '/LF', sellPhx: 5, sellTuc: 6, sellNorth: 6 },
      { key: 'gutters_dr', label: 'D&R Gutters', unit: '/LF', sellPhx: 18, sellTuc: 20, sellNorth: 20 },
      { key: 'gutters_rr', label: 'R&R Gutters', unit: '/LF', sellPhx: 25, sellTuc: 30, sellNorth: 30 },
      { label: 'Roof repairs minimum', unit: '/job', sellPhx: 1500, sellTuc: 1750 },
      { key: 'steep_8_9', label: 'Steep 8/12–9/12', unit: '/sq', sellPhx: 25, sellTuc: 25, sellNorth: 25 },
      { key: 'steep_9_11', label: 'Steep 10/12–11/12', unit: '/sq', sellPhx: 75, sellTuc: 75, sellNorth: 75 },
      { key: 'steep_11_12', label: 'Steep 12/12', unit: '/sq', sellPhx: 150, sellTuc: 150, sellNorth: 150 },
      {
        key: 'hip_ridge_high_profile',
        label: 'High profile hip & ridge',
        unit: '/job',
        sellPhx: HIGH_PROFILE_RIDGE_SELL,
        sellTuc: HIGH_PROFILE_RIDGE_SELL,
        sellNorth: HIGH_PROFILE_RIDGE_SELL,
      },
    ],
  },
  {
    title: 'Tile — sell',
    pane: 'labor',
    rows: [
      { key: 'tile_dr', label: 'Detach & Reset', unit: '/sq', sellPhx: 500, sellTuc: 550, sellNorth: 550 },
      { key: 'tile_rr', label: 'Remove & Replace', unit: '/sq', sellPhx: 900, sellTuc: 950, sellNorth: 950 },
      { label: 'SA / upgraded underlayment', unit: '/sq', sellPhx: 85, sellTuc: 100 },
    ],
  },
  {
    title: 'Foam / coating / flat — sell',
    pane: 'labor',
    rows: [
      { key: 'mod_bitumen', label: 'Modified bitumen', unit: '/sq', sellPhx: 600, sellTuc: 600 },
      { key: 'elastomeric', label: 'Elastomeric coating', unit: '/sq', sellPhx: 425, sellTuc: 450, sellNorth: 450, note: 'Mat cost TBD' },
      { key: 'silicone', label: 'Silicone coating', unit: '/sq', note: 'Sell + mat cost TBD' },
      { key: 'urethane', label: 'Urethane coating', unit: '/sq', note: 'Sell + mat cost TBD' },
      { key: 'coating', label: 'Coating (legacy)', unit: '/sq', sellPhx: 425, sellTuc: 450, sellNorth: 450 },
      { key: 'full_foam', label: 'Full foam', unit: '/sq', sellPhx: 650, sellTuc: 700, sellNorth: 700, note: 'Mat cost TBD' },
      { key: 'foam_overlay', label: 'Foam overlay', unit: '/sq', sellPhx: 575, sellTuc: 625, sellNorth: 625, note: 'Mat cost TBD' },
      { key: 'bur', label: 'Built-up (BUR)', unit: '/sq', note: 'Sell + mat cost TBD' },
      { key: 'iso_board', label: 'ISO board (fallback)', unit: '/sheet', note: 'Mat cost TBD' },
      { key: 'iso_4x8', label: 'ISO 4×8 sheet', unit: '/sheet', note: 'Covers 32 sq ft · mat cost TBD' },
      { key: 'iso_4x4', label: 'ISO 4×4 sheet', unit: '/sheet', note: 'Covers 16 sq ft · mat cost TBD' },
      { key: 'granules', label: 'Granules adder', unit: '/sq', note: 'Mat cost TBD' },
      { key: 'extra_spf', label: 'Extra inch SPF', unit: '/sq' },
      { key: 'scarify', label: 'Scarify', unit: '/sq' },
      { key: 'extra_pass', label: 'Additional coat', unit: '/sq' },
      { key: 'pressure_wash', label: 'Pressure wash & clean', unit: '/sq' },
    ],
  },
  {
    title: 'HVAC — sell',
    pane: 'labor',
    rows: [
      { key: 'hvac', label: 'D&R HVAC unit', unit: '/ea', sellPhx: 1300, sellTuc: 1600, sellNorth: 1600 },
    ],
  },
  {
    title: 'Labor costs & adders',
    pane: 'labor',
    rows: [
      { key: 'base_shingle', label: 'Base crew labor (shingle)', unit: '/sq', cost: 100 },
      { key: 'fascia_labor', label: 'Fascia labor', unit: '/LF', cost: 4 },
      { key: 'shingle_mold_labor', label: 'Shingle mold labor', unit: '/LF', cost: 4 },
      { key: 'cut_in_vent', label: 'Cut in vent labor', unit: '/ea', cost: 20 },
      { key: 'hvac_labor', label: 'D&R HVAC labor', unit: '/ea', cost: 900 },
      { key: 'steep_8_9', label: 'Steep labor 8/12–9/12', unit: '/sq', cost: 125 },
      { key: 'steep_10_11', label: 'Steep labor 10/12–11/12', unit: '/sq', cost: 175 },
      { key: 'steep_12', label: 'Steep labor 12/12', unit: '/sq', cost: 250 },
      { key: 'double_layer', label: 'Double layer', unit: '/sq', cost: 20 },
      { key: 'ridge_vent_labor', label: 'Ridge vent install', unit: '/LF', cost: 2 },
    ],
  },
  {
    title: 'Crew rates — Phoenix',
    pane: 'labor',
    rows: [
      { label: 'Maldonado', unit: '/sq', cost: 100 },
      { label: 'Crown Royal', unit: '/sq', cost: 100 },
      { label: 'Delgado', unit: '/sq', cost: 110 },
      { label: 'Mile High', unit: '/sq', cost: 100 },
      { label: 'EZ', unit: '/sq', cost: 105 },
      { label: 'TRC', unit: '/sq', cost: 120 },
      { label: 'Crew', unit: '/sq', cost: 110 },
      { label: 'JJ', unit: '/sq', cost: 105 },
      { label: 'Blueprint', unit: '/sq', cost: 130 },
      { label: 'G&M', unit: '/sq', cost: 120 },
      { label: 'Spearhead', unit: '/sq', cost: 110 },
      { label: 'My Way', unit: '/sq', cost: 100 },
      { label: 'Gleason', unit: '/sq', cost: 110 },
      { label: 'Rosales', unit: '/sq', cost: 115 },
      { label: 'ACI', unit: '/sq', cost: 110 },
      { label: 'Nailed It', unit: '/sq', cost: 120 },
    ],
  },
  {
    title: 'Crew contacts',
    pane: 'labor',
    rows: [
      { label: 'Manuel Maldonado', unit: '', note: '915-252-2646 · Maldonado' },
      { label: 'Sammy — Crown Royal', unit: '', note: '626-679-7194' },
      { label: 'Jesus Delgado', unit: '', note: '573-281-9441 · Delgado' },
      { label: 'Pancho Raigoza', unit: '', note: '303-995-6983 · Mile High' },
      { label: 'Sergio Quintanar', unit: '', note: '623-349-2515 · EZ' },
      { label: 'Josue Mtz', unit: '', note: '520-313-1641 · TRC' },
      { label: 'George Galvin', unit: '', note: '602-789-4358 · Crew' },
      { label: 'Joell Jaquez', unit: '', note: '602-471-3715 · JJ' },
      { label: 'Daniel Romero', unit: '', note: '520-548-9949 · Blueprint' },
      { label: 'Gerry Busta', unit: '', note: '520-336-1261 · G&M' },
      { label: 'Joe Jasso', unit: '', note: '480-979-2349 · Spearhead' },
      { label: 'Jesus Lugo', unit: '', note: '520-260-3276 · My Way' },
      { label: 'Joshua Hardin', unit: '', note: '336-306-3380 · Gleason' },
      { label: 'Chris Rosales Jr', unit: '', note: '480-749-8089 · Rosales' },
      { label: 'Hugo/Victor Rivera', unit: '', note: '928-310-1710 · Nailed It' },
      { label: 'Hunter Mainville', unit: '', note: '480-761-5674 · EV Foam' },
      { label: 'Fidel Cruz', unit: '', note: '480-352-6432 · Amber' },
      { label: 'Rick Amaral', unit: '', note: '602-561-1325 · Superior Foam' },
      { label: 'Travis Witt', unit: '', note: '602-908-6884 · Next Gen' },
    ],
  },
  {
    title: 'Shingles — book cost',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'cambridge', label: 'IKO Cambridge', unit: '/sq', cost: 89 },
      { key: 'dynasty', label: 'IKO Dynasty', unit: '/sq', cost: 94 },
      { key: 'armourshake', label: 'IKO Armourshake', unit: '/sq', cost: 230 },
      { key: 'gaf_hdz', label: 'GAF Timberline HDZ', unit: '/sq', cost: 130 },
      { key: 'gaf_natural_shadow', label: 'GAF Natural Shadow', unit: '/sq', cost: 129 },
      { key: 'owens_oakridge', label: 'Owens Corning Oakridge', unit: '/sq', cost: 110 },
      { key: 'owens_duration', label: 'Owens Corning Duration', unit: '/sq', cost: 118 },
      { key: 'owens_duration_designer', label: 'Owens Corning Duration Designer', unit: '/sq', cost: 118 },
      { key: 'certainteed_landmark', label: 'CertainTeed Landmark', unit: '/sq', cost: 117 },
      { key: 'certainteed_patriot_xl', label: 'CertainTeed Patriot XL', unit: '/sq', cost: 103 },
      { key: 'malarkey_highlander', label: 'Malarkey Highlander', unit: '/sq', cost: 154 },
      { key: 'malarkey_vista', label: 'Malarkey Vista', unit: '/sq', cost: 160 },
    ],
  },
  {
    title: 'Miller — decking',
    pane: 'materials',
    supplier: 'Miller',
    rows: [
      { key: 'osb', label: 'OSB 4×8 7/16"', unit: '/sheet', cost: 11 },
      { key: 'osb_1_2', label: 'OSB 4×8 1/2"', unit: '/sheet', cost: 11.5 },
      { key: 'cdx', label: 'CDX 4×8 7/16"', unit: '/sheet', cost: 20.5 },
      { key: 'cdx_1_2', label: 'CDX 4×8 1/2"', unit: '/sheet', cost: 31 },
    ],
  },
  {
    title: 'Miller — fascia & mold',
    pane: 'materials',
    supplier: 'Miller',
    rows: [
      { key: 'fascia_2x6_16', label: 'Prime combed fascia 2×6 × 16\'', unit: '/ea', cost: 27 },
      { key: 'fascia_2x6_20', label: 'Prime combed fascia 2×6 × 20\'', unit: '/ea', cost: 33.5 },
      { key: 'fascia_2x8_16', label: 'Prime combed fascia 2×8 × 16\'', unit: '/ea', cost: 36 },
      { key: 'fascia_2x8_20', label: 'Prime combed fascia 2×8 × 20\'', unit: '/ea', cost: 45 },
      { key: 'mold_1x2_16', label: 'Shingle mold 1×2 × 16\'', unit: '/pair', cost: 10.5, note: 'Order even qty' },
      { key: 'mold_1x3_16', label: 'Shingle mold 1×3 × 16\'', unit: '/pair', cost: 16 },
      { key: 'mold_1x4_16', label: 'Shingle mold 1×4 × 16\'', unit: '/pair', cost: 21 },
      { key: 'mold_1x6_16', label: 'Shingle mold 1×6 × 16\'', unit: '/pair', cost: 31.5 },
      { key: 'mold_1x8_16', label: 'Shingle mold 1×8 × 16\'', unit: '/pair', cost: 42 },
    ],
  },
  {
    title: 'SRS — drip edge',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'drip_2x2_color', label: '2"×2" Edge Color', unit: '/ea', cost: 9.1 },
      { key: 'drip_2x2_mill', label: '2"×2" Edge Mill', unit: '/ea', cost: 6.5 },
      { key: 'drip_2x4_color', label: '2"×4" Edge Color', unit: '/ea', cost: 12.9 },
      { key: 'drip_2x4_mill', label: '2"×4" Edge Mill', unit: '/ea', cost: 11.8 },
      { key: 'drip_3x3_color', label: '3"×3" Edge Color', unit: '/ea', cost: 14.15 },
      { key: 'drip_3x3_mill', label: '3"×3" Edge Mill', unit: '/ea', cost: 11.8 },
    ],
  },
  {
    title: 'SRS — pipe jacks',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'pipe_flash_1_5_al', label: '1.5" Pipe Flash Aluminum', unit: '/ea', cost: 18.65 },
      { key: 'pipe_flash_1_5_gal', label: '1.5" Pipe Flash Galvanized', unit: '/ea', cost: 7 },
      { key: 'pipe_flash_2_al', label: '2" Pipe Flash Aluminum', unit: '/ea', cost: 18.65 },
      { key: 'pipe_flash_2_gal', label: '2" Pipe Flash Galvanized', unit: '/ea', cost: 8 },
      { key: 'pipe_flash_3_al', label: '3" Pipe Flash Aluminum', unit: '/ea', cost: 17.35 },
      { key: 'pipe_flash_3_gal', label: '3" Pipe Flash Galvanized', unit: '/ea', cost: 9 },
      { key: 'pipe_flash_4_al', label: '4" Pipe Flash Aluminum', unit: '/ea', cost: 21.3 },
      { key: 'pipe_flash_4_gal', label: '4" Pipe Flash Galvanized', unit: '/ea', cost: 10 },
      { key: 'ttop_4_al', label: '4" T-Top Aluminum', unit: '/ea', cost: 18 },
      { key: 'ttop_4_gal', label: '4" T-Top Galvanized', unit: '/ea', cost: 9.7 },
      { key: 'ttop_7_al', label: '7" T-Top Aluminum', unit: '/ea', cost: 22.5 },
      { key: 'ttop_7_gal', label: '7" T-Top Galvanized', unit: '/ea', cost: 11.6 },
    ],
  },
  {
    title: 'SRS — vents',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'vent_brv34', label: 'BRV34 Bath Vent', unit: '/ea', cost: 35 },
      { key: 'vent_da4', label: 'DA-4 Vent', unit: '/ea', cost: 19.8 },
      { key: 'vent_kv68', label: 'KV68 Kitchen Vent', unit: '/ea', cost: 53 },
      { key: 'vent_lomanco_550', label: 'Lomanco 550', unit: '/ea', cost: 22.3 },
      { key: 'vent_lomanco_750', label: 'Lomanco 750 Mill', unit: '/ea', cost: 33 },
      { key: 'vent_ohagin_shingle', label: 'Ohagin Shingle Vent', unit: '/ea', cost: 39 },
      { key: 'vent_ohagin_tile', label: 'Ohagin Galvanized Tile Vent', unit: '/ea', cost: 45 },
      { key: 'vent_pro4', label: 'Pro-4 Vent', unit: '/ea', cost: 15.6 },
      { key: 'vent_lomanco_turbine_12', label: 'Lomanco 12" Turbine', unit: '/ea', cost: 82.5 },
      { key: 'vent_lomanco_lor', label: 'Lomanco LOR Ridgevent 12"×4\' (4 LF)', unit: '/ea', cost: 16.1, note: '~$4.03/LF' },
      { key: 'vent_lomanco_or9', label: 'Lomanco OR9-4 Ridgevent 9"×4\' (4 LF)', unit: '/ea', cost: 17.35, note: '~$4.34/LF' },
      { key: 'vent_lomanco_or30', label: 'Lomanco OR-30 Ridge Vent', unit: '/ea', cost: 131 },
      { key: 'ridge_vent', label: 'Ridge vent material', unit: '/LF', cost: 6, note: 'LOR/OR9-4 book ~$4/LF' },
    ],
  },
  {
    title: 'SRS — flat / MB',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'mb_cap_sheet', label: 'TopShield SA Cap Sheet', unit: '/sq', cost: 123 },
      { key: 'polyglass_sa_cap', label: 'Polyglass SA Cap Sheet', unit: '/sq', cost: 128 },
      { key: 'mb_base_ply', label: 'TopShield SA Base Sheet', unit: '/sq', cost: 126 },
      { key: 'glasbase_75', label: 'CertainTeed Glasbase #75 Base Sheet (3 sq)', unit: '/roll', cost: 61 },
      { key: 'polyglass_elastoflex_9', label: 'Polyglass Elastoflex SA V Flashing Strip 9"', unit: '/roll', cost: 52 },
    ],
  },
  {
    title: 'SRS — hip & ridge',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'hip_ridge_iko_std', label: 'IKO Hip & Ridge (standard)', unit: '/bdl', cost: 99.5 },
      { key: 'hip_ridge_iko_ultra', label: 'IKO Ultra Hip & Ridge (high profile)', unit: '/bdl', cost: 104 },
      { key: 'hip_ridge_oc_decoridge', label: 'Owens Corning DecoRidge (high profile)', unit: '/bdl', cost: 116 },
      { key: 'hip_ridge_ct_shadow', label: 'CertainTeed Shadow Ridge', unit: '/bdl', cost: 85 },
      { key: 'hip_ridge_gaf', label: 'GAF hip & ridge (standard)', unit: '/bdl', note: 'Cost TBD' },
      { key: 'hip_ridge_malarkey', label: 'Malarkey RidgeFlex (standard)', unit: '/bdl', note: 'Cost TBD' },
    ],
  },
  {
    title: 'SRS — starter',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'starter_iko', label: 'IKO Starter', unit: '/bdl', cost: 72 },
      { key: 'starter_iko_armour', label: 'IKO Armour Starter (70 LF/bdl)', unit: '/bdl', cost: 137 },
      { key: 'starter_gaf', label: 'GAF Pro-Start Starter', unit: '/bdl', cost: 73 },
      { key: 'starter_oc', label: 'Owens Corning Starter Shingle Strip', unit: '/bdl', cost: 84.5 },
      { key: 'starter_ct', label: 'CertainTeed Starter', unit: '/bdl', cost: 75 },
      { key: 'starter_malarkey', label: 'Malarkey Starter', unit: '/bdl', cost: 92.5 },
      { key: 'starter_topshield', label: 'TopShield Starter', unit: '/bdl', cost: 70.5 },
      { key: 'starter_tamko', label: 'Tamko Starter', unit: '/bdl', cost: 74 },
    ],
  },
  {
    title: 'SRS — underlayment (shingle)',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'felt_d4869', label: '15#/30# Felt ASTM D4869', unit: '/roll', cost: 32.25 },
      { key: 'felt_d226', label: '15#/30# Felt ASTM D226', unit: '/roll', cost: 39 },
      { key: 'tarah_40', label: 'Tarah 40# Organic Felt (2 sq)', unit: '/roll', cost: 38 },
      { key: 'cmi_ranger', label: 'CMI Ranger Synthetic (10 sq)', unit: '/roll', cost: 58 },
      { key: 'topshield_synthetic', label: 'TopShield Synthetic (10 sq)', unit: '/roll', cost: 67 },
      { key: 'prowest_synthetic', label: 'Prowest One Solutions Synthetic (~10 sq)', unit: '/roll', cost: 71, note: 'Private-label — confirm sq/roll w/ SRS' },
      { key: 'rhino_synthetic', label: 'Rhino Synthetic Underlayment (10 sq)', unit: '/roll', cost: 94.5 },
      { key: 'apoc_cxl', label: 'APOC CXL (4.5 sq)', unit: '/roll', cost: 95 },
      { key: 'topshield_100ht', label: 'TopShield 100HT (~10 sq HT)', unit: '/roll', cost: 108, note: 'Confirm SKU + sq/roll w/ SRS' },
      { key: 'gaf_feltbuster', label: 'GAF FeltBuster (10 sq)', unit: '/roll', cost: 119 },
      { key: 'topshield_sg_max_mts', label: 'TopShield SG Max MTS Synthetic (10 sq)', unit: '/roll', cost: 133 },
      { key: 'swiftguard', label: 'Swiftguard (10 sq)', unit: '/roll', cost: 206 },
      { key: 'titanium_udl_50', label: 'Titanium UDL 50 Synthetic (10 sq)', unit: '/roll', cost: 233 },
    ],
  },
  {
    title: 'SRS — ice & water / SA',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'topshield_defender', label: 'TopShield Defender Ice / CMI Securegrip Ice (2 sq)', unit: '/roll', cost: 89.5 },
      { key: 'iko_stormshield', label: 'IKO StormShield (~2 sq / 195 sf)', unit: '/roll', cost: 96.5 },
      { key: 'topshield_sg_ps_max', label: 'TopShield SG PS Max 2.0 HT Ice & Water (2 sq)', unit: '/roll', cost: 113 },
      { key: 'polyflex_sa_v', label: 'Polyglass Polyflex SA V (2 sq)', unit: '/roll', cost: 152 },
    ],
  },
  {
    title: 'SRS — tile field & underlay',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'eagle_tile', label: 'Eagle Concrete Tile', unit: '/sq', cost: 116.67 },
      { key: 'westlake_tile', label: 'Westlake Concrete Tile', unit: '/sq', cost: 114.35 },
      { key: 'clay_tile', label: 'Clay tile', unit: '/sq', note: 'Mat cost TBD' },
      { key: 'boral_organic_ply_40', label: 'Boral Organic Ply 40 (2 sq)', unit: '/roll', cost: 41.5 },
      { key: 'eagle_tru_2', label: 'Eagle Tru-2 (2 sq)', unit: '/roll', cost: 41.75 },
      { key: 'boral_ply_40', label: 'Boral Ply 40 (2 sq)', unit: '/roll', cost: 54.5 },
      { key: 'boral_tile_seal', label: 'Boral TileSeal (2 sq)', unit: '/roll', cost: 123 },
    ],
  },
  {
    title: 'SRS — tile hip & ridge / accessories',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'verde_p10_p20_hip', label: 'Verde P10/P20 Hip', unit: '/ea', cost: 45 },
      { key: 'verde_p15_p25_ridge', label: 'Verde P15/P25 Ridge', unit: '/ea', cost: 90 },
      { key: 'verde_p30_hip', label: 'Verde P30 Hip', unit: '/ea', cost: 53 },
      { key: 'verde_p35_ridge', label: 'Verde P35 Ridge', unit: '/ea', cost: 92 },
      { key: 'verde_p50_hip', label: 'Verde P50 Hip', unit: '/ea', cost: 49.75 },
      { key: 'verde_p55_ridge', label: 'Verde P55 Ridge', unit: '/ea', cost: 92 },
      { key: 'verde_pf7_flat', label: 'Verde PF7 Flat', unit: '/ea', cost: 99 },
      { key: 'westile_l_eave', label: 'Westile L-Style Eave Riser', unit: '/ea', cost: 8.4 },
      { key: 'birdstop_s', label: 'Birdstop "S"', unit: '/ea', cost: 9.6 },
      { key: 'birdstop_w', label: 'Birdstop "W"', unit: '/ea', cost: 9.6 },
      { key: 'verde_split_34', label: 'Verde Split Flashing 3/4"', unit: '/ea', cost: 26.9 },
      { key: 'verde_split_1_5', label: 'Verde Split Flashing 1-1/2"', unit: '/ea', cost: 25 },
      { key: 'verde_split_2', label: 'Verde Split Flashing 2"', unit: '/ea', cost: 25 },
      { key: 'westlake_trim', label: 'Westlake Trim', unit: '/ea', cost: 3.99 },
      { key: 'eagle_trim', label: 'Eagle Trim', unit: '/ea', cost: 3.95 },
      { key: 'kwikmix_mortar', label: 'Kwikmix Mortar Pre-Mix', unit: '/bag', cost: 14.6 },
    ],
  },
  {
    title: 'SRS — fasteners',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'fast_roof_nails_50', label: 'Roofing Nails 50#', unit: '/box', cost: 76.5 },
      { key: 'fast_tile_nails_50', label: 'Tile Nails 50#', unit: '/box', cost: 76.5 },
      { key: 'fast_coil_1_25', label: '1.25" Coil Nails', unit: '/box', cost: 49 },
      { key: 'fast_coil_1_75', label: '1-3/4" Coil Nails', unit: '/box', cost: 56 },
      { key: 'fast_cap_nails_1_5', label: '1" Metal Cap Nails 5#', unit: '/box', cost: 18.85 },
      { key: 'fast_cap_nails_1_50', label: '1" Metal Cap Nails 50#', unit: '/box', cost: 102 },
      { key: 'fast_plastic_cap', label: '1" Plastic Cap Nails', unit: '/box', cost: 18 },
      { key: 'fast_n17', label: '1-1/2" N-17 Staples', unit: '/box', cost: 59 },
      { key: 'fast_a11', label: '3/8" A11 Staples', unit: '/box', cost: 5.9 },
      { key: 'fast_p10', label: '5/8" P-10 Staples', unit: '/box', cost: 57 },
    ],
  },
  {
    title: 'SRS — flashing & accessories',
    pane: 'materials',
    supplier: 'SRS',
    rows: [
      { key: 'w_valley_24x10', label: '24"×10\' 3-Rib W-Valley', unit: '/ea', cost: 33.1 },
      { key: 'counter_flash_1', label: '#1 Counter Flashing', unit: '/ea', cost: 10.9 },
      { key: 'z_bar_2x1_5x2', label: '2"×1-1/2"×2" Z-Bar', unit: '/ea', cost: 9.45 },
      { key: 'gravel_stop_2x4', label: '2"×4" Low Rise Gravel Stop', unit: '/ea', cost: 12.9 },
      { key: 'roof_to_wall_2x6', label: '2"×6" Roof to Wall', unit: '/ea', cost: 11.2 },
      { key: 'flash_3in1', label: '3-in-1', unit: '/ea', cost: 12.8 },
      { key: 'step_flash_4x4x8', label: '4"×4"×8" Step Flashing (~100/box)', unit: '/box', cost: 54.5, note: 'Confirm pcs/box w/ SRS' },
      { key: 'pan_flashing', label: 'Pan Flashing', unit: '/ea', cost: 16.5 },
      { key: 'cement_101_3', label: 'Tropical #101 Plastic Cement 3 gal', unit: '/pail', cost: 35 },
      { key: 'cement_101_5', label: 'Tropical #101 Plastic Cement 5 gal', unit: '/pail', cost: 47 },
      { key: 'mastic_509_3', label: 'Tropical #509 Modified Mastic 3 gal', unit: '/pail', cost: 39 },
      { key: 'mastic_509_5', label: 'Tropical #509 Modified Mastic 5 gal', unit: '/pail', cost: 61 },
      { key: 'flashing_paint', label: 'TopShield Shingle Flashing Paint 12 oz', unit: '/can', cost: 10 },
      { key: 'caulking', label: 'Caulking', unit: '/tube', cost: 10 },
      { key: 'furring_1x2x4', label: 'Furring Strips 1"×2"×4\'', unit: '/bundle', cost: 13.5, note: 'Confirm pcs/bundle w/ SRS' },
      { key: 'karnak_405_5', label: 'Karnak 405 5 gal', unit: '/pail', cost: 103 },
      { key: 'karnak_505_5', label: 'Karnak 505 5 gal', unit: '/pail', cost: 112 },
      { key: 'karnak_505_wb_3_5', label: 'Karnak 505 WB 3.5 gal', unit: '/pail', cost: 124 },
      { key: 'polyglass_pg700_5', label: 'Polyglass PG700 5 gal', unit: '/pail', cost: 87.5 },
      { key: 'tropical_901_hs', label: 'Tropical #901 HS White', unit: '/pail', cost: 81 },
      { key: 'foam_granules', label: 'Foam granules (~30 lb/sq)', unit: '/bag', note: 'Mat cost TBD' },
      { key: 'foam_primer', label: 'Foam primer (~0.5 gal/sq)', unit: '/gal', note: 'Mat cost TBD' },
      { key: 'foam_top_coating', label: 'Foam top coating', unit: '/gal', note: 'Mat cost TBD' },
    ],
  },
];
